version: "3.8"

services:

  api:
    build: ..
    container_name: rag_api
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}

  ui:
    build: ..
    container_name: rag_ui
    command: streamlit run ui/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
